pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - yarn install
              - yarn run build
        - step:
            name: Code linting
            script:
              - yarn install eslint
              - npx eslint .
            caches:
              - node
        - step:
            name: "Deployment to Canary"
            script:
              - pipe: atlassian/ftp-deploy:0.3.7
                variables:
                  USER: "percepat"
                  PASSWORD: "C7mL#92bwEaM*7"
                  SERVER: "103.147.154.57"
                  REMOTE_PATH: "master.percepatanweb.site"
                # LOCAL_PATH: '<string>' # Optional
                # DEBUG: '<boolean>' # Optional
                # EXTRA_ARGS: '<string>' # Optional.
                # DELETE_FLAG: '<boolean>' # Optional.
