# For more information: https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml
# Maintainer: Ezra Lazuardy <ezralucio@gmail.com>
definitions:
  steps:
    - step: &build-project-canary
        image: cypress/base:16.14.2
        name: Build and Test Project
        script:
          # setup host
          - export CI=false
          - export DEBIAN_FRONTEND=noninteractive
          - ln -snf /usr/share/zoneinfo/$TIMEZONE /etc/localtime && echo $TIMEZONE > /etc/timezone

          # setup environment variables
          - sed -i 's/REACT_APP_API_URL=/REACT_APP_API_URL=https:\/\/test.api.daksoftware.nl/' .env.pipeline
          - ln -f -s .env.pipeline .env

          # install yarn dependencies
          - yarn global add serve wait-on
          - yarn --production=false --frozen-lockfile

          # build project
          - rm -rf build && yarn build

          # run application
          - serve -s build -l 3000 & wait-on http://localhost:3000

pipelines:
  branches:
    master:
      - step:
          name: "Deployment to Master"
          script:
            - pipe: atlassian/ftp-deploy:0.3.7
              variables:
                USER: "percepat"
                PASSWORD: "C7mL#92bwEaM*7"
                SERVER: "103.147.154.57"
                REMOTE_PATH: "master.percepatanweb.site"
              # LOCAL_PATH: '<string>' # Optional
              # DEBUG: '<boolean>' # Optional
              # EXTRA_ARGS: '<string>' # Optional.
              # DELETE_FLAG: '<boolean>' # Optional.
